// <auto-generated />
using System;
using InfoTrack.Solicitors.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfoTrack.Solicitors.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718094309_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfoTrack.Solicitors.Data.Entities.LocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "London"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Birmingham"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Leeds"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Sheffield"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Bradford"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Bristol"
                        });
                });

            modelBuilder.Entity("InfoTrack.Solicitors.Data.Entities.SearchRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SearchRuns");
                });

            modelBuilder.Entity("InfoTrack.Solicitors.Data.Entities.SearchRunLocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResultCount")
                        .HasColumnType("int");

                    b.Property<int>("SearchRunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SearchRunId");

                    b.ToTable("SearchRunLocations");
                });

            modelBuilder.Entity("InfoTrack.Solicitors.Data.Entities.SolicitorListingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailFormUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBasicListing")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("SearchRunLocationId")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SearchRunLocationId");

                    b.ToTable("SolicitorListings");
                });

            modelBuilder.Entity("InfoTrack.Solicitors.Data.Entities.SolicitorQualityMarkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MarkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitorListingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolicitorListingId");

                    b.ToTable("SolicitorQualityMarks");
                });

            modelBuilder.Entity("InfoTrack.Solicitors.Data.Entities.SearchRunLocationEntity", b =>
                {
                    b.HasOne("InfoTrack.Solicitors.Data.Entities.SearchRunEntity", "SearchRun")
                        .WithMany("Locations")
                        .HasForeignKey("SearchRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchRun");
                });

            modelBuilder.Entity("InfoTrack.Solicitors.Data.Entities.SolicitorListingEntity", b =>
                {
                    b.HasOne("InfoTrack.Solicitors.Data.Entities.SearchRunLocationEntity", "SearchRunLocation")
                        .WithMany("Listings")
                        .HasForeignKey("SearchRunLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchRunLocation");
                });

            modelBuilder.Entity("InfoTrack.Solicitors.Data.Entities.SolicitorQualityMarkEntity", b =>
                {
                    b.HasOne("InfoTrack.Solicitors.Data.Entities.SolicitorListingEntity", "SolicitorListing")
                        .WithMany("QualityMarks")
                        .HasForeignKey("SolicitorListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitorListing");
                });

            modelBuilder.Entity("InfoTrack.Solicitors.Data.Entities.SearchRunEntity", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("InfoTrack.Solicitors.Data.Entities.SearchRunLocationEntity", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("InfoTrack.Solicitors.Data.Entities.SolicitorListingEntity", b =>
                {
                    b.Navigation("QualityMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
